config/routes.rb
Rails.application.routes.draw do
  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users
    resources :verses
    resources :home, only: :index
    resources :script, only: :index
    resources :books, only: :show do
      collection do
        get 'search'
      end
    end
    get "/books/:book_id/:chapter_id" => 'chapters#show', as: :chapter
    root to: 'home#index'
  end
  get '*path', to: redirect("/#{I18n.default_locale}/%{path}")
  get '', to: redirect("/#{I18n.default_locale}")

end

app/models/script.rb
# == Schema Information
#
# Table name: scripts
#
#  id         :integer          not null, primary key
#  book       :integer
#  chapter    :integer
#  line       :integer
#  body       :text
#  created_at :datetime
#  updated_at :datetime
#

class Script < ActiveRecord::Base
  include SearchCop

  scope :current_chapter, ->(book_id) { select('DISTINCT chapter').where(book: book_id).order(:chapter) }
  scope :current_script, ->(book_id, chapter_id) { select(:body).where(book: book_id, chapter: chapter_id).order(:id) }

  self.search_scope :search do
    attributes :body
  end

  def book_name(book_number)
    Book::BOOKS[book_number.to_s]
  end

  def self.create(a = {})
    puts "Saved record with: book: #{a[:book]}, chapter: #{a[:chapter]}, line: #{a[:line]}, body: #{a[:body]}"
  end

end

app/controllers/script_controller.rb
class ScriptController < ApplicationController

  def index
  end

end

app/views/script/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="navbar-inner">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "#{t "back"}", root_path, :class => 'navbar-brand' %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <%= link_to new_verse_path, :class => "btn btn-primary navbar-btn", :type => 'button', :id => "custom-btn" do %>
            <span class="glyphicon glyphicon-plus"></span>
            <span class="glyphicon glyphicon-font"></span>
          <% end %>
        </ul>
        <%= form_tag verses_path && url_for(:controller => 'books', :action => 'search'), :method => 'get', :class => 'navbar-form navbar-left', :role => 'search' do %>
          <div class="form-group">
            <%= text_field_tag :search, params[:search], :class => 'form-control', :id => "search-bar", :placeholder => "#{t "search"}", :type=>"search" %>
          </div>
          <div class="form-group">
            <%= button_tag(type:"submit", class:"btn btn-default", :id => "submit", :name => nil, :alt => "Search") do %>
              <span><%= t "search" %> </span><span class="glyphicon glyphicon-search"></span>
            <% end %>
            <%= link_to "/script", :class => 'btn btn-default', :type => 'button', :alt => 'Clear'  do %>
              <span class="glyphicon glyphicon-remove"></span>
            <% end %>
          </div>
        <% end %>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </div>
</nav>

app/views/script/index.html.erb
<%= render 'header' %>

<div class="container">
  <h3><%= t "script.choose_book" %></h3>
  <div class="row">
    <div class="col-md-6">
      <table class="table table-hover table-condensed table-striped">
        <thead>
          <tr>
            <th><%= t "script.hebrew_scripture" %></th>
          </tr>
        </thead>

        <tbody>
        <% Book::BOOKS.first(39).each do |id, name| %>
          <tr>
            <td><%= link_to name, book_path(id) %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-md-6">
      <table class="table table-hover table-condensed table-striped">
        <thead>
          <tr>
            <th><%= t "script.greek_scripture" %></th>
          </tr>
        </thead>

        <tbody>
        <% Book::BOOKS.to_a.last(27).each do |id, name| %>
          <tr>
            <td><%= link_to name, book_path(id) %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/script/search.html.erb
<%= render 'header' %>

<div class="container">
  <h3>Search in your Verses:</h3>
  <table class="table table-hover table-condensed table-striped">
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Label</th>
      </tr>
    </thead>

    <tbody>
      <% @verses.each do |verse| %>
        <tr>
          <td><%= link_to verse.title, edit_verse_path(verse) %></td>
          <td><%= verse.description %></td>
          <td><%= verse.label %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
</br>
<div class="container">
  <div id="vertical-line"></div>
</div>
</br>
<div class="container">
  <h3>Search in Bible:</h3>
  <table class="table table-hover table-condensed table-striped">
    <thead>
      <tr>
        <th>Book</th>
        <th>Chapt.</th>
        <th>Ver.</th>
        <th>Content:</th>
      </tr>
    </thead>

    <tbody>
      <% @scripts.each do |text| %>
        <tr>
          <td><%= text.book_name(text.book) %></td>
          <td><%= text.chapter %></td>
          <td><%= text.line %></td>
          <td><%= text.body %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/script/show.html.erb
<div class="container">
  <h3>Search in Bible:</h3>
  <table class="table table-hover table-condensed table-striped">
    <thead>
      <tr>
        <th>Book</th>
        <th>Chapt.</th>
        <th>Ver.</th>
        <th>Content:</th>
      </tr>
    </thead>

    <tbody>
        <tr>
          <td><%= @script %></td>
        </tr>
    </tbody>
  </table>
</div>