config/routes.rb
Rails.application.routes.draw do
  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users
    resources :verses
    resources :home, only: :index
    resources :script, only: :index
    resources :books, only: :show do
      collection do
        get 'search'
      end
    end
    get "/books/:book_id/:chapter_id" => 'chapters#show', as: :chapter
    root to: 'home#index'
  end
  get '*path', to: redirect("/#{I18n.default_locale}/%{path}")
  get '', to: redirect("/#{I18n.default_locale}")

end

app/models/book.rb
class Book < ActiveRecord::Base
  BOOKS = {
    "1" => "Rodzaju",
    "2" => "Wyjścia",
    "3" => "Kapłańska",
    "4" => "Liczb",
    "5" => "Powtórzonego Prawa",
    "6" => "Jozuego",
    "7" => "Sędziów",
    "8" => "Rut",
    "9" => "1 Samuela",
    "10" => "2 Samuela",
    "11" => "1 Królów",
    "12" => "2 Królów",
    "13" => "1 Kronik",
    "14" => "2 Kronik",
    "15" => "Ezdrasza",
    "16" => "Nehemiasza",
    "17" => "Estery",
    "18" => "Hioba",
    "19" => "Psalmy",
    "20" => "Przysłów",
    "21" => "Kaznodziei",
    "22" => "Pieśń",
    "23" => "Izajasza",
    "24" => "Jeremiasza",
    "25" => "Lamentacje",
    "26" => "Ezechiela",
    "27" => "Daniela",
    "28" => "Ozeasza",
    "29" => "Joela",
    "30" => "Amosa",
    "31" => "Abdiasza",
    "32" => "Jonasza",
    "33" => "Micheasza",
    "34" => "Nahuma",
    "35" => "Habakuka",
    "36" => "Sofoniasza",
    "37" => "Aggeusza",
    "38" => "Zachariasza",
    "39" => "Malachiasza",
    "40" => "Mateusza",
    "41" => "Marka",
    "42" => "Łukasza",
    "43" => "Jana",
    "44" => "Dzieje Apostolskie",
    "45" => "Rzymian",
    "46" => "1 Koryntian",
    "47" => "2 Koryntian",
    "48" => "Galatów",
    "49" => "Efezjan",
    "50" => "Filipian",
    "51" => "Kolosan",
    "52" => "1 Tesaloniczan",
    "53" => "2 Tesaloniczan",
    "54" => "1 Tymoteusza",
    "55" => "2 Tymoteusza",
    "56" => "Tytusa",
    "57" => "Filemona",
    "58" => "Hebrajczyków",
    "59" => "Jakuba",
    "60" => "1 Piotra",
    "61" => "2 Piotra",
    "62" => "1 Jana",
    "63" => "2 Jana",
    "64" => "3 Jana",
    "65" => "Judy",
    "66" => "Objawienia"
  }

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
  end

  def search
    @scripts = Script.search(params[:search])
    @verses = current_user.verses.search(params[:search])
  end

end

app/views/books/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="navbar-inner">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "#{t "back"}", "/script", :class => 'navbar-brand' %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <%= link_to new_verse_path, :class => "btn btn-primary navbar-btn", :type => 'button', :id => "custom-btn" do %>
            <span class="glyphicon glyphicon-plus"></span>
            <span class="glyphicon glyphicon-font"></span>
          <% end %>
        </ul>
        <%= form_tag verses_path && url_for(:controller => 'books', :action => 'search'), :method => 'get', :class => 'navbar-form navbar-left', :role => 'search' do %>
          <div class="form-group">
            <%= text_field_tag :search, params[:search], :class => 'form-control', :id => "search-bar", :placeholder => "#{t "search"}", :type=>"search" %>
          </div>
          <div class="form-group">
            <%= button_tag(type:"submit", class:"btn btn-default", :id => "submit", :name => nil, :alt => "Search") do %>
              <span><%= t "search" %> </span><span class="glyphicon glyphicon-search"></span>
            <% end %>
            <%= link_to "/script", :class => 'btn btn-default', :type => 'button', :alt => 'Clear'  do %>
              <span class="glyphicon glyphicon-remove"></span>
            <% end %>
          </div>
        <% end %>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </div>
</nav>

app/views/books/index.html.erb
<div class="container">
  <h3><%= t "books.search_in_bible" %></h3>
  <table class="table table-hover table-condensed table-striped">
    <thead>
      <tr>
        <th><%= t "books.book" %></th>
      </tr>
    </thead>

    <tbody>
      <% Book::BOOKS.each do |id, name| %>
        <tr>
          <td><%= link_to name, books_path(id) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/books/search.html.erb
<%= render :partial => 'chapters/header' %>

<div class="container">
  <h3><%= t "books.results_in_your_verses" %></h3>
  <table class="table table-hover table-condensed table-striped">
    <thead>
      <tr>
        <th><%= t "title" %></th>
        <th><%= t "description" %></th>
        <th><%= t "label" %></th>
      </tr>
    </thead>

    <tbody>
      <% @verses.each do |verse| %>
        <tr>
          <td><%= link_to verse.title, edit_verse_path(verse) %></td>
          <td><%= verse.description %></td>
          <td><%= verse.label %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
</br>
<div class="container">
  <div id="vertical-line"></div>
</div>
</br>
<div class="container">
  <h3><%= t "books.results_in_bible" %></h3>
  <table class="table table-hover table-condensed table-striped">
    <thead>
      <tr>
        <th><%= t "books.book" %></th>
        <th><%= t "books.chapter" %></th>
        <th><%= t "books.verse" %></th>
        <th><%= t "books.content" %></th>
      </tr>
    </thead>

    <tbody>
      <% @scripts.each do |text| %>
        <tr>
          <td><%= text.book_name(text.book) %></td>
          <td><%= text.chapter %></td>
          <td><%= text.line %></td>
          <td><%= text.body %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/books/show.html.erb
<%= render 'header' %>

<div class="container">
  <h3><%= t "books.choose_chapter" %></h3>

  <div class="btn-toolbar">
  <% Script.current_chapter(params[:id]).each do |chapter| %>
    <%= link_to chapter.chapter, chapter_path(params[:id], chapter.chapter), :class => "btn btn-default", :type => "button", :id => "verse-btn" %>
  <% end %>
  </div>
</div>