config/routes.rb
Rails.application.routes.draw do
  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users
    resources :verses
    resources :home, only: :index
    resources :script, only: :index
    resources :books, only: :show do
      collection do
        get 'search'
      end
    end
    get "/books/:book_id/:chapter_id" => 'chapters#show', as: :chapter
    root to: 'home#index'
  end
  get '*path', to: redirect("/#{I18n.default_locale}/%{path}")
  get '', to: redirect("/#{I18n.default_locale}")

end

app/controllers/verses_controller.rb
class VersesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_verse, only: [:show, :edit, :update, :destroy]

  # GET /verses
  # GET /verses.json
  def index
    @verses = current_user.verses
  end

  # GET /verses/1
  # GET /verses/1.json
  def show
  end

  # GET /verses/new
  def new
    @verse = Verse.new
  end

  # GET /verses/1/edit
  def edit
  end

  # POST /verses
  # POST /verses.json
  def create
    @verse = current_user.verses.new(verse_params)

    respond_to do |format|
      if @verse.save
        format.html { redirect_to @verse, notice: 'Verse was successfully created.' }
        format.json { render :show, status: :created, location: @verse }
      else
        format.html { render :new }
        format.json { render json: @verse.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /verses/1
  # PATCH/PUT /verses/1.json
  def update
    respond_to do |format|
      if @verse.update(verse_params)
        format.html { redirect_to @verse, notice: 'Verse was successfully updated.' }
        format.json { render :show, status: :ok, location: @verse }
      else
        format.html { render :edit }
        format.json { render json: @verse.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /verses/1
  # DELETE /verses/1.json
  def destroy
    @verse.destroy
    respond_to do |format|
      format.html { redirect_to verses_url, notice: 'Verse was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_verse
      @verse = Verse.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def verse_params
      params.require(:verse).permit(:title, :description, :label)
    end
end

app/helpers/verses_helper.rb
module VersesHelper
  def label_select(verse)
    select_tag(
      "label_select",
      options_for_select(current_user.verses.pluck(:label).uniq),
      :class => 'string required',
      :name => 'verse[label]',
      :id => "verse_label",
      :include_blank => false
    )
  end
end

app/views/verses/_form.html.erb
<%= simple_form_for @verse, :html => { :class => 'form'
  } do |f| %>
  <div class="form-group">
    <%= f.input :title, :type => "title", :class => "form-cotrol", :label => "#{t "title"}", :placeholder => "#{t "title"}" %>
  </div>
  <div class="form-group">
    <%= f.input :description, :type => "description", :class => "form-cotrol", :label => "#{t "description"}", :placeholder => "#{t "description"}" %>
  </div>
  <div id='add_new_label'>
    <%= f.input :label, :type => "label", :class => "form-control", :label => "#{t "label"}", :placeholder => "#{t "label"}" %>
  </div>
  <div class="form-group">
    <div id='select_label' hidden>
      <div class='control-group string required verse_label'>
        <label class="text required control-label" for="verse_label">
          <abbr title="required">* </abbr><%= t "label" %></label>
        <div class='controls'>
          <%= label_select(@verse) %>
        </div>
      </div>
    </div>
  </div>
  <div class="form-group">
    <a href='javascript:void(0)', class='controls btn btn-default', id='create_new_label', hidden><%= t "verses.create_new_label" %></a>
  </div>
  <div class="form-group">
    <a href='javascript:void(0)', class='controls', id='use_existing_label', alt='use_existing_label'><%= t "verses.use_existing_label" %></a>
  </div>
  <div class="form-group">
    <%= f.submit "#{t "verses.create_verse"}", :class => "btn btn-primary" %>
  </div>
<% end %>

<script>
  $("select#verse_label").attr('disabled', 'true');
  $("#create_new_label").hide();
  $("#create_new_label").click(function(e) {
    e.stopPropagation();
    $("#add_new_label").show();
    $("select#verse_label").attr('disabled', 'true');
    $("#create_new_label").hide();
    $("#use_existing_label").show();
    $("#select_label").hide()
    $("input#verse_label").removeAttr('disabled');
  });

  $("#use_existing_label").click(function(e) {
    e.stopPropagation();
    $("#add_new_label").hide();
    $("input#verse_label").attr('disabled', 'true');
    $("select#verse_label").removeAttr('disabled');
    $("#create_new_label").show();
    $("#use_existing_label").hide();
    $("#select_label").show()
  });
</script>

app/views/verses/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="navbar-inner">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <%= link_to "#{t "back"}", verses_path, :class => 'navbar-brand'%>
      </div>
    </div><!-- /.container-fluid -->
  </div>
</nav>
</br>

app/views/verses/edit.html.erb
<%= render 'header' %>
<h2><%= t "verses.editing_verse" %></h2>

<%= render 'form' %>
</br>
</br>
<%= link_to "#{t "verses.delete_verse"}", @verse, method: :delete, :class => "btn btn-danger", :alt => "Delete verse" %>

app/views/verses/index.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="navbar-inner">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "ScriptureSaver", root_path, :class => 'navbar-brand'%>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "#{t "verses.logged_as" } #{current_user.email}", 'javascript:;' %></li>
          <li><%= button_to "#{t "verses.sign_out" }", destroy_user_session_path, :method => :delete, :class => 'btn btn-danger navbar-btn', :id => 'custom-btn' %></li>
        </ul>
      </div>
    </div>
  </div>
</nav>
<div class="container">
  <h2><%= t "verses.your_verses" %></h2>
</div>
<div class="container">
  <%= form_tag verses_path && url_for(:controller => 'books', :action => 'search'), :method => 'get', :role => 'search' do %>
    <div class="form-group">
      <%= text_field_tag :search, params[:search], :class => 'form-control', :id => "search-bar", :placeholder => "#{t "search"}", :type=>"search" %>
    </div>
    <div class="btn-group">
      <%= button_tag(type:"submit", class:"btn btn-default", :name => nil, :id => "submit") do %>
        <span><%= t "search" %> </span><span class="glyphicon glyphicon-search"></span>
      <% end %>
      <%= link_to new_verse_path, :class => "btn btn-primary", :type => 'button', :alt => 'New Verse' do %>
        <span class="glyphicon glyphicon-plus"></span>
        <span class="glyphicon glyphicon-font"></span>
      <% end %>
      <%= link_to script_index_path, :class => "btn btn-default", :type => 'button', :alt => 'Bible' do %>
        <span class="glyphicon glyphicon-book"></span>
      <% end %>
    </div>
  <% end %>
</div>
</br>
<div class="container">
  <table class="table table-hover table-condensed table-striped">
    <thead>
      <tr>
        <th><%= t "title" %></th>
        <th><%= t "description" %></th>
        <th><%= t "label" %></th>
      </tr>
    </thead>

    <tbody>
      <% @verses.each do |verse| %>
        <tr>
          <td><%= link_to verse.title, edit_verse_path(verse) %></td>
          <td><%= verse.description %></td>
          <td><%= verse.label %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/verses/new.html.erb
<%= render 'header' %>
<h2><%= t "verses.new_verse" %></h2>

<%= render 'form' %>

app/views/verses/show.html.erb
<%= render 'header' %>

<h4><%= @verse.title %> | <small><%= @verse.label %></small></h4>

<blockquote>
  <%= @verse.description %>
</blockquote>

<%= link_to "#{t "verses.edit_verse"}", edit_verse_path(@verse), :class => "btn btn-default" %>